### ISSUE TITLE
Allow clerk to function behind a proxy / bundle dependencies in a release

### ISSUE THREAD

**Issue by zackteo** [nextjournal/clerk#147]
https://github.com/nextjournal/clerk/issues/30

This is linked to the above issue in my work environment. However, in my work environment while we can download maven dependencies through a certain system, we will not be able to access links like "https://storage.googleapis.com/nextjournal-cas-eu" 

Which seems to be a necessity as soon as `(require '[nextjournal.clerk :as clerk])` is ran

**Comment by shyamkovuri3** [comment]
same issue , blocker to user clerk at work behind proxy

**Comment by mk** [comment]
Hi @ikappaki,

Since its initial release, Clerk didn't bundle all assets in the jar but load them in the browser on demand. What changed with `v0.7.416` is that we also load a resource manifest on the JVM to look up the url of those assets.

> Other than it seems inappropriate, in general, for libraries to download objects in the background without users being aware of it, it impacts apps behind firewalls or offline for whatever reason (no wifi, running clerk in isolation in a container etc).

Work is in progress on making Clerk work when offline in #113.

> It is common for corporate firewalls to allow http access only to browsers, and make it either difficult or impossible for any other process to access the internet.

I wasn't aware of this distinction. So you can access https in the browser just fine, but not via the JVM?

We were going for an cache on first use rather than bundling things up in the jar in #113 because folks can also dynamically require js libraries like in [this example](https://snapshots.nextjournal.com/clerk/build/e19de7ee3befdba2adb645bfafbf097a2f5f12ae/index.html#/notebooks/viewer_d3_require.clj) and we could support those for offline use as well.

We could consider to bundle the set of commonly used libs inside the jar at the cost of introducing a pretty different code path for when Clerk is consumed via a jar vs a git lib. Another smaller change to consider is to bundle the resource manifest inside Clerk still use the browser to serve the files. It sounds like this would work in your case but then Clerk would still not work when offline.

Curious to hear how widespread the issue is and what other workarounds exist.

**Comment by mk** [comment]
> Another smaller change to consider is to bundle the resource manifest inside Clerk still use the browser to serve the files. It sounds like this would work in your case but then Clerk would still not work when offline.

Another option that I thought of now: not do any requests from the JVM but let the browser cache assets on first use using using a [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API), possibly via [Workbox](https://developer.chrome.com/docs/workbox/precaching-with-workbox/#precaching-with-generatesw).

**Comment by ikappaki** [comment]
> Since its initial release, Clerk didn't bundle all assets in the jar but load them in the browser on demand. What changed with `v0.7.416` is that we also load a resource manifest on the JVM to look up the url of those assets.

this explains it then :)
 
> > Other than it seems inappropriate, in general, for libraries to download objects in the background without users being aware of it, it impacts apps behind firewalls or offline for whatever reason (no wifi, running clerk in isolation in a container etc).
> 
> Work is in progress on making Clerk work when offline in #113.

Sounds great, though it appears as if an internet connection is required at least once at first invocation to cache the assets (this wouldn't work for example if Clerk was a dep in a test container with no internet connectivity).

> 
> > It is common for corporate firewalls to allow http access only to browsers, and make it either difficult or impossible for any other process to access the internet.
> 
> I wasn't aware of this distinction. So you can access https in the browser just fine, but not via the JVM?

Correct, I believe this is normal practice, organisations would still like for people behind a firewall to access the web for their work (given the browser is a very well managed application), but will restrict everything else.

> We were going for an cache on first use rather than bundling things up in the jar in #113 because folks can also dynamically require js libraries like in [this example](https://snapshots.nextjournal.com/clerk/build/e19de7ee3befdba2adb645bfafbf097a2f5f12ae/index.html#/notebooks/viewer_d3_require.clj) and we could support those for offline use as well.
> 
> We could consider to bundle the set of commonly used libs inside the jar at the cost of introducing a pretty different code path for when Clerk is consumed via a jar vs a git lib. Another smaller change to consider is to bundle the resource manifest inside Clerk still use the browser to serve the files. It sounds like this would work in your case but then Clerk would still not work when offline.

It appears to me that the ideal solution would be to bundle the standard assets with the jar so that Clerk works out of the box without any need for connectivity (as with any other library whose design does not require an internet connection to load I guess), and let any dymamic loading assets require an internet connectivity to function (this seems to be a design requirement).

Yes, I believe bundling the manifest with the jar (as opposed to requesting at load time) will solve the majority of proxy issues with users, since they are most likely to have access to a browser with Internet connectivity.

> Curious to hear how widespread the issue is and what other workarounds exist.

Is there a possibility perhaps to package the assets in a separate package so that people who wish to including them as a dependency on demand?

Why is it that the assets not bundle with Clerk to begin with? Was it perhaps the assets size consideration?

Thanks for the quick reply!

**Comment by ikappaki** [comment]
> Another option that I thought of now: not do any requests from the JVM but let the browser cache assets on first use using using a [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API), possibly via [Workbox](https://developer.chrome.com/docs/workbox/precaching-with-workbox/#precaching-with-generatesw) (which seems to power the offline functionality of [many js frameworks](https://developer.chrome.com/docs/workbox/framework-integrations/)).

Yes, this sounds like a good idea too getting around proxying restrictions

**Comment by ikappaki** [comment]
Hi @zackteo, @shyamkovuri3 

could you please advise whether you can access the following url from your web browser at work? I made the assumption in my discussion above that people generally can access the Internet behind the firewall via their browser, and it is only when trying to download it by other means (i.e. when clerk trying to make a direction connection to the internet from the jvm) that the problem manifests itself. Or is that you can't connect to google storage even from within the browser where you casually browse the web from?

https://storage.googleapis.com/nextjournal-cas-eu

Thanks

**Comment by borkdude** [comment]
This issue should now be solved with clerk `{:mvn/version "0.8.467"}`. Note that we still load from the internet when clerk is used as a git dep, but when used as a mvn dep, the problem should no longer happen. Please let us know.

**Comment by ikappaki** [comment]
Tnanks @borkdude. I can confirm it works now with `0.8.470`.

**Comment by shyamkovuri3** [comment]
Tnanks @borkdude and clerk contributors.
