### ISSUE TITLE
Seems to hang on infinite sequences

### ISSUE THREAD

**Issue by tekacs** [nextjournal/clerk#15]
## Replication steps

user.clj:
```clojure
(ns user
  (:require [nextjournal.clerk :as clerk]))

(clerk/serve! {:watch-paths ["notebooks"]})
```

notebooks/tester.clj:
```clojure
(range)
```

This seems to hang, rather than handling the infinite sequence as expected and called out in the example here: https://github.com/nextjournal/clerk/blob/fd79f7504ebffaa27958e4e05264b0ad2f650182/notebooks/viewer_api.clj#L12

Clerk server launched with Calva's jack-in, with no other dependencies. The Clerk server seems to just stop responding to updates.

On the other hand `(range 100)` seems to work fine.

**Comment by mk** [comment]
Hey, thanks for the report! Clerk currently has a condition to not cache things that execute in under 1ms, see
https://github.com/nextjournal/clerk/blob/fd79f7504ebffaa27958e4e05264b0ad2f650182/src/nextjournal/clerk.clj#L66-L67

and

https://github.com/nextjournal/clerk/blob/fd79f7504ebffaa27958e4e05264b0ad2f650182/src/nextjournal/clerk.clj#L107

Could you maybe experiment with raising that limit and printing the time in order to find out what a better threshold is?

I think we might also want to put some limits in place so we by default don't try to freeze uncountable seqs with a very large number of items.
