### ISSUE TITLE
Print output limited to first page

### ISSUE THREAD

**Issue by silasdavis** [nextjournal/clerk#266]
I would like to use `clerk` to generate a PDF that can be combined into a broader data pack thingy.

I've tried printing to PDF from browsers but the browsers I have tested (Brave, Firefox) both only print a single page so it is heavily truncated.

Any idea on how I might get a 
nice PDF output, or what would be required to implement such a feature?

Example:

https://github.clerk.garden/nextjournal/clerk-demo/commit/cb212b2edc64e762bcd1af56417ef9f6b2fde5b1/notebooks/data_science.html

produces:

[clerk.pdf](https://github.com/nextjournal/clerk/files/9962274/clerk.pdf)

**Comment by jackrusher** [comment]
Sorry, generating PDF is out of scope for Clerk. I recommend that you investigate other third party HTML->PDF solutions for this purpose.

**Comment by jackrusher** [comment]
@behrica Yeah, there's something weird going on with the viewport in the rendered HTML. We intend to fix it, but it's also not a top priority atm.

**Comment by joe-loco** [comment]
That only the first page was printing has already been fixed with https://github.com/nextjournal/clerk/commit/0bf24372b0fed5be6bf01ffb7c04b2e254526077. I’ve added a bunch of additional print styles (see 1709741a4a8c2837735f7ceae8763f654ef6a394) that hide superfluous elements, improve font size, &c, and try to avoid breaking in between elements (with medium success because browser sometimes enforce their own heuristics).
