### ISSUE TITLE
Hyperlinks with a `#` are incorrectly parsed

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#383]
I tried to insert the following link: [#2](https://github.com/mentat-collective/leva.cljs/issues/2)

and noticed that clerk resolves it as `2` without the `#`, and inserts a link to `#2` on the page:

<img width="135" alt="image" src="https://user-images.githubusercontent.com/69635/211633211-34863e19-d015-40e5-b52a-7dd5fd9803ed.png">

If I add a SECOND pound sign, I get proper rendering, but the link still leads to `#2` on the page:

<img width="118" alt="image" src="https://user-images.githubusercontent.com/69635/211633244-6a82c55f-c87d-4d00-9654-729ea3331e1f.png">

This doesn't happen on GitHub, so it seems like it's not a markdown spec problem.

**Comment by zampino** [comment]
That's kind of expected, but probably not correct: `#tag` expressions are parsed as _hashtags_:

```clj 
(nextjournal.markdown/parse "#2")
=>
{:type :doc,
 :content [{:type :paragraph, :content [{:type :hashtag, :text "2"}]}],
 :nextjournal.markdown.parser/id->index {},
 :toc {:type :toc}}
```

and rendered in Clerk according to the viewer: 
```clj
{:name :nextjournal.markdown/hashtag 
 :transform-fn (into-markup #(vector :a {:href (str "#" (:text %))}))}
```
and the text of the link is the text of the hashtag node, without the leading `#` but we could change that.

I think in github it "works" because it links to an existing issue, this #999999 is parsed as text as per [commonmark strict](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%232%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22debug%22%7D%7D).
