### ISSUE TITLE
`{:nextjournal.clerk/visibility {:code :fold}}` before `ns` declaration hides table of contents.

### ISSUE THREAD

**Issue by teodorlu** [nextjournal/clerk#483]
Hi!

I'm on `io.github.nextjournal/clerk {:mvn/version "0.13.842"}`.

I found some possibly weird behavior. This behaves like I expect:

```clj
;; # Clerk repro

(ns mikrobloggeriet.newdoc
  {:nextjournal.clerk/toc true})

{:nextjournal.clerk/visibility {:code :fold}}

;; ## First section
```

Screenshot:
![image](https://github.com/nextjournal/clerk/assets/5285452/f40fffe1-aa4e-4793-850d-786f7a35ae52)

This looks weird:

```clj
;; # Clerk repro

{:nextjournal.clerk/visibility {:code :fold}}

(ns mikrobloggeriet.newdoc
  {:nextjournal.clerk/toc true})

;; ## First section
```

Screenshot:

![image](https://github.com/nextjournal/clerk/assets/5285452/28fd83bc-570a-4e46-b7fa-e0c0d8b01381)

The table of contents seems to have disappeared.

Is this expected behavior?

**Comment by mk** [comment]
Hi @teodorlu,

Yes, this is intentional. We currently look at the first form to derive the doc settings. In your second example this would be `{:nextjournal.clerk/visibility {:code :fold}}` so the table of contents setting is ignored. The settings marker should really only be used at the start of the document if you don't have a namespace. We should probably clarify this in the book.

I'm not sure we should warn or error when this happens as I feel it can be useful for changing settings temporarily?

**Comment by teodorlu** [comment]
> The settings marker should really only be used at the start of the document if you don't have a namespace. 

Aaah, I hadn't catched that.

> We should probably clarify this in the book.

That seems like a good idea to me.

> I'm not sure we should warn or error when this happens as I feel it can be useful for changing settings temporarily?

Not sure. I think about this under "how do we teach the user to use Clerk correctly?". If I was making Clerk, I'd probably start with a paragraph in the book about it, and take it from there.

A small warning with "you seem to be doing X, which is not recommended. Please read this section of the book to understand the toplevel settings form" could make sense, but it's more work.

**Comment by teodorlu** [comment]
Up to you if you want to close this issue or not!

I was able to fix my misconception, thanks for that. I'd gladly read over a section in the book about this if you decide to write a section in the book about document settings.
