### ISSUE TITLE
:fold visibility removes code styling

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#526]
See the drawer at the bottom of https://emmy-viewers.mentat.org/dev/examples/manifold/pq_knot:

<img width="761" alt="image" src="https://github.com/nextjournal/clerk/assets/69635/777a7565-9292-4271-8910-0517860e9409">

This is with Clerk `"1f6c5331418aaf9c5a4335fc2e6e95f07dc3af6b"`.

**Comment by mk** [comment]
This has indeed been an issue with 1f6c5331418aaf9c5a4335fc2e6e95f07dc3af6b, see our static build
https://snapshots.nextjournal.com/clerk/build/1f6c5331418aaf9c5a4335fc2e6e95f07dc3af6b/index.html#/notebooks/visibility.clj

But it's since been fixed in the following commit 051e4f2b0dd4143a41f68df6912dd651e41f99f4 https://snapshots.nextjournal.com/clerk/build/051e4f2b0dd4143a41f68df6912dd651e41f99f4/index.html#/notebooks/visibility.clj
