### ISSUE TITLE
editor mode doesn't apply unquotes

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#576]
Given a notebook with this:

```clojure
`(do ~'x)
```

In Clojure, this evaluates correctly to `(do x)`. But in Clerk's editor mode, I see the following:

<img width="303" alt="image" src="https://github.com/nextjournal/clerk/assets/69635/675ddf95-d5d3-42b4-824c-a7909725871a">

Unquotes aren't correctly resolved.

**Comment by mk** [comment]
@borkdude do I understand the [recent #sci thread on slack](https://clojurians.slack.com/archives/C015LCR9MHD/p1700859497692659) correctly in that we need to manually add unquote-splicing for this to work? Note that editor mode is a browser-only variant of clerk that's powered by sci, [demo here](https://snapshots.nextjournal.com/clerk/build/ad8e5a2c19aa55921ea357fa9005d563f80c53be/editor/).

**Comment by borkdude** [comment]
@mk I don't understand what this has to do with the above issue?

**Comment by borkdude** [comment]
I'll take a look at this issue today

**Comment by borkdude** [comment]
This is a rewrite-clj node -> s-expr issue. Note that this is not necessarily a rewrite-clj bug since not all strings can be represented as s-expressions without information loss.

E.g. you cannot represent `::s` as an s-expression and keeping it as an unresolved auto-qualified keyword. The same is true for syntax-quotes since they need to be resolved at read time using the environment you're qualifying symbols in.

As such I recommend transforming to forms at a later stage than what is done currently, the later the better and using `sci/parse-string` rather than `edamame` directly since that will correctly resolve symbols in syntax quote.

**Comment by borkdude** [comment]
This PR seems to work:

https://github.com/nextjournal/clerk/pull/578

<img width="756" alt="Screenshot 2023-11-27 at 11 56 00" src="https://github.com/nextjournal/clerk/assets/284934/1aaeca1e-d717-4e65-b89a-78664c43eaac">
