### ISSUE TITLE
Make defn in cherry work with `eval-cljs` again

### ISSUE THREAD

**Issue by mk** [nextjournal/clerk#719]
As part of #713 in f920ceeba73a545f080216576a63ed85c72c3479  I changed two forms in the cherry notebook from `eval-cljs` to `eval-cljs-str`. I haven't figured out why one works while the other doesn't and the comment from the notebook makes me thing `eval-cljs` should not work:

> Because s-expressions serialized to the client currently don't preserve metadata in clerk, and  async functions need `^:async`, we use a plain string.

But I'm pretty sure it did work before and the comment did not apply anymore. See also the static build on the commit before https://snapshots.nextjournal.com/clerk/build/0ae7ec0734eee89c6e0608486a54424f81f5b03c/index.html#/notebooks/cherry

@borkdude is that something you could look at?

**Comment by borkdude** [comment]
I tried to repro locally and had some issues: it looked like with `eval-cljs` sometimes the form would be evaluated using SCI instead of cherry, but eventually I couldn't repro it anymore. Perhaps caching issues?
Anyway, I reverted `eval-cljs-str` to `eval-cljs` and the static notebook now seems to work again:

https://snapshots.nextjournal.com/clerk/build/3a6e9a5eddc2bca207a72c4cc4b7e63653225006/index.html#/notebooks/cherry

**Comment by borkdude** [comment]
PR here: https://github.com/nextjournal/clerk/pull/720

**Comment by mk** [comment]
Strange, a Heisenbug. Does it still work after clearing the clerk cache? Could you also adjust the comment regarding the async metadata? Does cherry not need that anymore?

**Comment by borkdude** [comment]
The `defn` macro supports adding metadata via a normal expression, rather than via metadata, which was fixed in cherry a while back. I'll try what you suggested.

**Comment by borkdude** [comment]
Works after calling `(clerk/clear-cache!)`. Removed comment.
